---
# defaults file for minikube
minikube_dependencies:
  - python-lxml
  - python-libvirt
  - qemu-kvm
  - firewalld
  - libvirt-daemon-system
  - dnsmasq

minikube_install_dir: /usr/local/bin
minikube_version: latest
kubectl_version: v1.15.0
docker_version: v18.09.7
